default:
  image: golang:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build-bot
    - make build-reporter

test:
  stage: test
  script:
    - make test

lint:
  stage: test
  script:
    - make lint
