run:
  timeout: 1m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  golint:
    min-confidence: 0
  gocognit:
    min-complexity: 30
  dupl:
    threshold: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  revive:
    rules:
      - name: unexported-return
        disabled: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gocognit
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - megacheck
    - revive
    - typecheck
    - unparam

issues:
  exclude-rules:
    - path: 'storage\/postgresql\/test_vars\.go'
      linters:
        - unused
    - path: '(.+)_test\.go'
      linters:
        - gocognit

  exclude:
    # _ instead of err checks
    - G104
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
