{
 "title": "Fin Assistance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS by command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(finassist_telegram_response_time_seconds_sum[$__rate_interval]) / rate(finassist_telegram_response_time_seconds_count[$__rate_interval])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Commands rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(finassis_telegram_commands_total[$__rate_interval])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "RPS quantiles [add]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"add\"}[$__rate_interval])))",
     "legendFormat": "q0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"add\"}[$__rate_interval])))",
     "legendFormat": "q0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"add\"}[$__rate_interval])))",
     "legendFormat": "q0.5"
    }
   ]
  },
  {
   "title": "RPS quantiles [report]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"report\"}[$__rate_interval])))",
     "legendFormat": "q0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"report\"}[$__rate_interval])))",
     "legendFormat": "q0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"report\"}[$__rate_interval])))",
     "legendFormat": "q0.5"
    }
   ]
  },
  {
   "title": "RPS quantiles [currency]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"currency\"}[$__rate_interval])))",
     "legendFormat": "q0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"currency\"}[$__rate_interval])))",
     "legendFormat": "q0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"currency\"}[$__rate_interval])))",
     "legendFormat": "q0.5"
    }
   ]
  },
  {
   "title": "RPS quantiles [set-currency]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"set-currency\"}[$__rate_interval])))",
     "legendFormat": "q0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"set-currency\"}[$__rate_interval])))",
     "legendFormat": "q0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"set-currency\"}[$__rate_interval])))",
     "legendFormat": "q0.5"
    }
   ]
  },
  {
   "title": "RPS quantiles [limit]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"limit\"}[$__rate_interval])))",
     "legendFormat": "q0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"limit\"}[$__rate_interval])))",
     "legendFormat": "q0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"limit\"}[$__rate_interval])))",
     "legendFormat": "q0.5"
    }
   ]
  },
  {
   "title": "RPS quantiles [start]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"start\"}[$__rate_interval])))",
     "legendFormat": "q0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"start\"}[$__rate_interval])))",
     "legendFormat": "q0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(finassist_telegram_response_time_seconds_bucket{command=\"start\"}[$__rate_interval])))",
     "legendFormat": "q0.5"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Idle Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "finassist_database_idle_connections{}",
     "legendFormat": "idle"
    },
    {
     "expr": "finassist_database_max_open_connections{}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Acquire Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(finassist_database_wait_duration_seconds[$__rate_interval])",
     "legendFormat": "{{db_name}}"
    }
   ]
  }
 ]
}